// Fix: Created content for databaseService.ts with initial data.
import { Donor, Establishment, Requester, Request } from '../types';
import { BADGES } from '../constants/gamification';

const initialDonors: Donor[] = [
    {
        id: 'don-1',
        userType: 'donor',
        username: 'john.doe',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        password: 'password123',
        dateOfBirth: '1990-05-15',
        gender: 'male',
        bloodGroup: 'O+',
        phone: '123-456-7890',
        wilaya: 'Alger',
        commune: 'Alger Centre',
        profilePictureUrl: 'https://i.pravatar.cc/150?u=john.doe',
        donationHistory: [
            { id: 'd-1', establishmentName: 'Hôpital Mustapha Pacha', date: '2023-11-01', quantity: 1, reason: 'Voluntary' },
            { id: 'd-2', establishmentName: 'Clinique El Chifa', date: '2023-07-15', quantity: 1, reason: 'Voluntary' }
        ],
        points: 200,
        badges: [BADGES[0]],
    },
    {
        id: 'don-2',
        userType: 'donor',
        username: 'jane.smith',
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@example.com',
        password: 'password123',
        dateOfBirth: '1995-08-20',
        gender: 'female',
        bloodGroup: 'A-',
        phone: '987-654-3210',
        wilaya: 'Oran',
        commune: 'Oran',
        profilePictureUrl: 'https://i.pravatar.cc/150?u=jane.smith',
        donationHistory: [
            { id: 'd-3', establishmentName: 'Hôpital d\'Oran', date: '2024-01-10', quantity: 1, reason: 'Voluntary' }
        ],
        points: 100,
        badges: [BADGES[0]],
    },
     {
        id: 'don-test',
        userType: 'donor',
        username: 'donortest',
        firstName: 'Test',
        lastName: 'Donor',
        email: 'donor@test.com',
        password: 'password',
        dateOfBirth: '1992-01-01',
        gender: 'male',
        bloodGroup: 'A+',
        phone: '111-222-3333',
        wilaya: 'Alger',
        commune: 'Alger Centre',
        donationHistory: [],
        points: 0,
        badges: [],
    },
];

const initialEstablishments: Establishment[] = [
    {
        id: 'est-1',
        userType: 'establishment',
        username: 'chu_mustapha',
        name: 'Hôpital Mustapha Pacha',
        email: 'contact@mustapha.dz',
        password: 'password123',
        type: 'Hôpital',
        phone: '021-23-45-67',
        wilaya: 'Alger',
        commune: 'Sidi M\'Hamed',
        address: 'Place du 1er Mai, Sidi M\'Hamed',
        latitude: 36.7633,
        longitude: 3.0594,
        googleMapsUrl: 'https://maps.app.goo.gl/abcdefg'
    },
    {
        id: 'est-2',
        userType: 'establishment',
        username: 'clinique_chifa',
        name: 'Clinique El Chifa',
        email: 'contact@chifa.dz',
        password: 'password123',
        type: 'Clinique',
        phone: '023-98-76-54',
        wilaya: 'Alger',
        commune: 'El Biar',
        address: '12 Rue des Jasmins, El Biar',
        latitude: 36.7761,
        longitude: 3.0238,
    },
     {
        id: 'est-test',
        userType: 'establishment',
        username: 'establishmenttest',
        name: 'Test Establishment',
        email: 'establishment@test.com',
        password: 'password',
        type: 'Hôpital',
        phone: '444-555-6666',
        wilaya: 'Alger',
        commune: 'Alger Centre',
        address: '123 Test Street',
        latitude: 36.77,
        longitude: 3.06,
    },
];

const initialRequesters: Requester[] = [
    {
        id: 'req-1',
        userType: 'requester',
        username: 'karim.b',
        firstName: 'Karim',
        lastName: 'Benali',
        email: 'karim.b@email.com',
        password: 'password123',
        phone: '555-123-456',
        wilaya: 'Constantine',
        commune: 'Constantine',
    },
     {
        id: 'req-test',
        userType: 'requester',
        username: 'requestertest',
        firstName: 'Test',
        lastName: 'Requester',
        email: 'requester@test.com',
        password: 'password',
        phone: '777-888-9999',
        wilaya: 'Alger',
        commune: 'Alger Centre',
    },
];

const initialRequests: Request[] = [
    {
        id: 'req-blood-1',
        authorId: 'est-1',
        authorName: 'Hôpital Mustapha Pacha',
        bloodGroup: 'A+',
        quantity: 5,
        urgency: 'Urgent',
        wilaya: 'Alger',
        commune: 'Sidi M\'Hamed',
        notes: 'Besoin urgent pour une opération chirurgicale.',
        status: 'Open',
        createdAt: '2024-05-20T10:00:00Z',
        establishmentName: 'Hôpital Mustapha Pacha',
        contactName: 'Hôpital Mustapha Pacha',
        contactPhone: '021-23-45-67',
        latitude: 36.7633,
        longitude: 3.0594,
        responses: ['don-2'],
        approvedDonors: []
    },
    {
        id: 'req-blood-2',
        authorId: 'req-1',
        authorName: 'Karim Benali',
        bloodGroup: 'O-',
        quantity: 2,
        urgency: 'Normal',
        wilaya: 'Constantine',
        commune: 'Constantine',
        notes: 'Pour un membre de ma famille.',
        status: 'Open',
        createdAt: '2024-05-18T15:30:00Z',
        establishmentName: 'Clinique Ibn Sina',
        contactName: 'Karim Benali',
        contactPhone: '555-123-456',
        responses: [],
        approvedDonors: []
    },
];

export const getInitialData = () => ({
    initialDonors,
    initialEstablishments,
    initialRequesters,
    initialRequests,
});